name: 'Dump Environment'
description: 'Simple python action that dumps the environment'

# definition how we want our action
runs:
  using: docker # we are saying this action will run on docker
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.
