name: Test Workflow
on:
  issues:
    types: [labeled]
jobs:
  first-job:
    if: github.event.label.name == 'scheduled'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Action
        uses: ./
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}} # default token in GitHub Workflow